import = ["/home/mike/.config/alacritty/themes/gruvbox_dark.toml"]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
y = 1

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.97

[window.padding]
x = 8
y = 8
